### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by kacphur** [Kieranmcm07/SQA-Higher-Assigment-Computing-Science-Python#1]
YOLOS, yk you cant be posting your assignment up online as it can get you in trouble, lolsies, but good luck on the assignment, I done it this year and it seems I have similarly replicated it! :)
![image](https://github.com/Nokky07/SQA-Higher-Assigment-Computing-Science-Python/assets/90797543/b44c0186-4535-40e8-97ef-6c3baabe1dc3)

**Comment by Kieranmcm07** [comment]
Thank you. I have forgotten to make the repository on private.
